name: RegEx Returning Results
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    
    - name: Run script against sample targets, write to results.txt
      run: ./bashHog.sh ./testfiles results.txt
    
    - name: Check if each rule returns one result, if not fail build
      run: |
        RULES=$(cat results.txt | grep 'Results' | wc -l)
        RESULTS=$(cat results.txt | grep -v 'Results' | wc -l)
        if [ "$RULES" -ne "$RESULTS" ]; then exit 1; else exit 0; fi
